spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
Diz pro Hibernate (JPA) qual tipo de banco você está usando.

spring.datasource.driver-class-name=org.postgresql.Driver
É a classe Java que faz a conexão com o PostgreSQL.

spring.datasource.username=postgres
spring.datasource.password=ruandb

spring.datasource.url=jdbc:postgresql://localhost:5432/meubanco
Isso define:protocolo, host, porta, nome do banco

spring.jpa.generate-ddl=true
liz pro JPA gerar o schema (estrutura do banco) baseado nas entidades.

spring.jpa.hibernate.ddl-auto=update
Controla o que o Hibernate faz com o banco:
none → não faz nada
create → recria tudo (apaga dados)
create-drop → cria e apaga ao fechar
update → atualiza sem apagar dados (o seu)

spring.jpa.show-sql=true
Mostra no console os SQLs que o Hibernate está executando.
select * from usuario;